### ISSUE TITLE
Repository deprecations and removals

### ISSUE THREAD

**Issue by rflavien** [objective-php/rfc#2]
# ObjectivePHP RFC: Repository deprecations and removals

>  * Version: 0.1
>  * Date: 2018-01-10
>  * Author: Flavien Rodrigues, rodrigues.flavien@gmail.com
>  * Status: Draft

## Summary

Some components or official packages are not useful. Others are still in an early state for a will. That's why I suggest to clear the ObjectivePHP GitHub organisation group by deleting some repositories.

### Repositories to delete
- objective-php/bootstrap-package
- objective-php/html
- objective-php/serializer

NOTE: as `objective-php/bootstrap-package` is an empty repository, it can be deleted without deprecation step.

### Deprecation
Add the GitHub topic `DEPRECATED` on the repository.
Update the README.md with : `This repository is deprecated and will be remove in v2.0.0`

#### objective-php/html
Add in `ObjectivePHP\Html\Tag::__construct` :
```php
@trigger_error("The objective-php/html component is deprecated and will be remove in v2.0.0", E_USER_DEPRECATED);
```

#### objective-php/serializer
Add in `ObjectivePHP\Serializer::__construct` : 
```php
@trigger_error("The objective-php/serializer component is deprecated and will be remove in v2.0.0", E_USER_DEPRECATED);
```
## Backward Incompatible Changes

What breaks, and what is the justification for it?

## Proposed Objective PHP Version(s)

Deprecation in 1.2.0
Delete in 2.0.0

### To Components

Describe the impact to the core components.

### To Packages

Describe the impact to the packages.

### To Workflow

Describe any new workflow steps and/or steps modifications required by this proposal (if applies), so they can be accurately and comprehensively explained in the framework documentation.

### To Configuration

Describe any new configuration directive so they can be accurately and comprehensively explained in the framework documentation.

## Future Scope

This sections details areas where the feature might be improved in future, but that are not currently proposed in this RFC.

## Proposed Voting Choices

Include these so readers know where you are heading and can discuss the proposed voting options.

State whether this project requires a 2/3 or 50%+1 majority

## Links to external references, discussions, issues or RFCs

**Comment by gauthier** [comment]
@rflavien I'm not sure why you would like to remove `html`. I understand this is not the more interesting component of ObjectivePHP, but it is used in several other components (and also in the `showcase` and `starter-kit`, so I guess this will be kind of dangerous to drop it.

**Comment by rflavien** [comment]
Will be defined by 2.0.0 goals.
